# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyShoppingCart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyShoppingCart


 pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'GoogleSignIn'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Storage'



  target 'MyShoppingCartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyShoppingCartUITests' do
    # Pods for testing
  end

end
